### ISSUE TITLE
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by Syeph0n** [MackinationsAi/sd-webui-udav2#10]
Running on Windows 10 with Forge using the correct sd-forge-udav2 extension file.

Getting this TypeError any time I attempt to compute depth.

```python
Traceback (most recent call last):
  File "E:\Programs2\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\Programs2\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Programs2\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\blocks.py", line 1919, in process_api
    inputs = await self.preprocess_data(
  File "E:\Programs2\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\blocks.py", line 1650, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "E:\Programs2\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\components\image.py", line 197, in preprocess
    return image_utils.format_image(
  File "E:\Programs2\webui_forge_cu124_torch24\system\python\lib\site-packages\gradio\image_utils.py", line 30, in format_image
    path = processing_utils.save_pil_to_cache(
TypeError: save_pil_to_file() got an unexpected keyword argument 'name'
```

I also checked to make sure my install of Forge is up to date, which is it.

**Comment by MackinationsAi** [comment]
That has to do w/ the latest gradio update, if you downgrade gradio>=4.44.1 the error will go away. I build this extension before gradio made major updates & some functionalities broke past 4.44.1. Once I have some time off from work I will be updated it to function w/ gradio 5.0.0 & above.

**Comment by wzol** [comment]
Are there any updates on this? You have made a great extension, I'd love to use it.
