### ISSUE TITLE
SD-Forge Error

### ISSUE THREAD

**Issue by Lesteriax** [MackinationsAi/sd-webui-udav2#4]
After installing and restarting, once I click compute, it gives me below error. I have waited 3 minutes and tried removing and adding it again, still getting the same error. I tried manually downloading the models but I do not know where is the location of the checkpoints file.

Traceback (most recent call last):
  File "D:\ai-webuis\stable-forge\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ai-webuis\stable-forge\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\ai-webuis\stable-forge\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ai-webuis\stable-forge\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ai-webuis\stable-forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\ai-webuis\stable-forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ai-webuis\stable-forge\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\ai-webuis\stable-forge\webui\extensions\sd-webui-udav2\scripts\upgraded_depth_anything_v2.py", line 255, in on_submit_single
    colourized_filenames, grey_depth_filename = process_image(image, colour_map_method, encoder, selection)
  File "D:\ai-webuis\stable-forge\webui\extensions\sd-webui-udav2\scripts\upgraded_depth_anything_v2.py", line 95, in process_image
    model = load_model(encoder)
  File "D:\ai-webuis\stable-forge\webui\extensions\sd-webui-udav2\scripts\upgraded_depth_anything_v2.py", line 44, in load_model
    checkpoint_path = modelloader.load_file_from_url(checkpoint_url, model_dir=checkpoints_dir, file_name=checkpoint_filename, hash_prefix=sha256)
TypeError: load_file_from_url() got an unexpected keyword argument 'hash_prefix'

**Comment by MackinationsAi** [comment]
Based on this error snippet - I think the reason for the error is you are using (File "D:\ai-webuis\stable-forge\webui\extensions\ ```sd-webui-udav2``` \scripts\upgraded_depth_anything_v2.py) extension meant for a1111. When using forge you need to install the ```sd-forge-udav2``` extension, which can be found in this [release package here](https://github.com/MackinationsAi/sd-webui-udav2/releases/tag/sd-forge-udav2_v0.0.3) specifically for forge. I also made some minor updates to the code just now & tested it, no hash_prefix error, so you should be good to go. Just follow the instructions for installing the forge extension version from the link to the release page above, & thanks for alerting me to this error!

**Comment by Lesteriax** [comment]
Thanks! works perfectly now
